apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
stringData:
  kestrel-password: "Pa55word"
  require-email-verification: "true"
  network-credential-username: "srki.miki@gmail.com"
  network-credential-password: "twshdabuaclmjkfw"
  redirect-email-to-credential-username: "true"
  smtp-client-host: "smtp.gmail.com"
  smtp-client-port: "25"
  send-email-notifications: "true"
  client-url: "http://localhost:4200"
  jwt-secret: "1234567890123456"
  kestrel-path: "/https/aspnetapp.pfx"